@startuml
!define RECTANGLE class

package "Presentation Layer" {
    RECTANGLE GameRestController
    RECTANGLE UserRestController
    RECTANGLE AchievementRestController
}

package "Business Logic Layer" {
    RECTANGLE GameService
    RECTANGLE AchievmenentService
    RECTANGLE CardService
    RECTANGLE HandService
    RECTANGLE PackCardService
    RECTANGLE PlayerService
    RECTANGLE TableCardService
    RECTANGLE CellService
    RECTANGLE UserService
    RECTANGLE AuthoritiesService
    RECTANGLE RowService
}

package "Resources Layer" {
    class UserRepository {
        - Optional<User> findByUsername(String username)
        - Boolean existsByUsername(String username)
        - Optional<User> findById(Integer id)
        - Iterable<User> findAllByAuthority(String auth)
        - Iterable<Player> findAllPlayerByUser(User user)
    }
    class AuthoritiesRepository {
        - Optional<Authorities> findByName(String authority)
    }
    class GameRepository {
        - Optional<Game> findById(Integer id)
        - List<Game> findByGameStateIn(List<GameState> gameStates)
        - Optional<Game> findGameByGameCode(String gameCode)
    }
    class AchievementRepository {

    }
    class CardRepository {

    }
    class HandRepository {

    }
    class PackCardRepository {

    }
    class PlayerRepository {
        - Iterable<Game> findAllGameByPlayer(Player player)
    }
    class TableCardRepository {

    }
    class CellRepository {

    }
    class RowRepository {

    }
}

' Connections from Presentation Layer to Business Logic Layer
GameRestController -.-> GameService
GameRestController -.-> UserService
GameRestController -.-> PlayerService
GameRestController -.-> HandService
GameRestController -.-> TableCardService
GameRestController -.-> PackCardService
GameRestController -.-> CardService
GameRestController -.-> CellService

UserRestController -.-> UserService
UserRestController -.-> AuthoritiesService
UserRestController -.-> PlayerService

AchievementRestController -.-> AchievmenentService
AchievementRestController -.-> UserService

' Connections from Business Logic Layer to Resources Layer
GameService -down-> GameRepository
AchievmenentService -down-> AchievementRepository
AchievmenentService -down-> UserRepository
CardService -down-> CardRepository
HandService -down-> HandRepository
PackCardService -down-> PackCardRepository
PlayerService -down-> PlayerRepository
TableCardService -down-> TableCardRepository
UserService -down-> UserRepository
AuthoritiesService -down-> AuthoritiesRepository
CellService -down-> CellRepository
RowService -down-> RowRepository

' Internal Business Logic Layer connections
GameService -down-> PackCardService
GameService -down-> HandService
PackCardService -down-> CardService
PackCardService -down-> PlayerService
TableCardService -down-> CellService
TableCardService -down-> CardService
TableCardService -down-> PlayerService
TableCardService -down-> RowService

' Styles



@enduml
